### ISSUE TITLE
Seeing warning for altool deprecation.

### ISSUE THREAD

**Issue by nsrCodes** [electron/notarize#137]
I was getting the usual error while trying to build my app _(as documented in #33)_
But this time it had the extra warning of:

```
Warning: altool has been deprecated for notarization and starting in late 2023 will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software. (-1030)
```

Just wanted to bring this into the attention of the maintainers.

P.S. _would be willing to contribute if possible_. Meanwhile this issue can be used to track more info about this.

**Comment by nickcernis** [comment]
`notarize()` defaults to altool ('legacy') by default, but it seems you can already configure it to use `notarytool` instead:

https://github.com/electron/notarize/blob/295c39d8c0ec21efa282161c667576fc7cb39558/README.md?plain=1#L44-L62

**Comment by philjones88** [comment]
Following as Apple sent out emails today around the deprecation of altool...

```
We’re reaching out because you recently used the altool command-line utility to notarize your macOS software with Apple. As announced last year at WWDC22, if you’re still using altool with the Apple notary service, you should transition to the notarytool command-line utility as soon as possible. Notarizing software with altool was deprecated in Xcode 13, and the Apple notary service will no longer accept uploads from altool as of November 1, 2023. Existing notarized software will continue to function properly.

For information on notarizing your apps, read TechNote TN3147: Migrating to the latest notarization tool.

If you have any questions, contact us.

Apple Developer Relations

```

Will test overriding default of legacy altool...

**Comment by thegnuu** [comment]
@philjones88 I switched from the deprecated `electron-notarize` to this and made a quick test.

```
CloudKit query for [...] failed due to "Record not found".
Could not find base64 encoded ticket in response [...]
The staple and validate action failed! Error 65.
```

I used the `appleId`/`appleIdPassword` authentication in my test.
Not sure what to do in this case and I have not found any useful information online, but maybe someone can point me in the right direction :)

But I realized that it is not working with `legacy` as well - unfortunately, I have no time to look at it in more detail right now since I have to publish a new version, so I will just switch back to `electron-notarize` for now. I will have a look at it as soon as I have some time.

**Comment by thegnuu** [comment]
Quick follow-up, I just realized that `electron-builder` uses this plugin internally, so I removed my custom code and set up `electron-builder` to use the `notarytool` settings of this package and everything worked perfectly!

**Comment by MarshallOfSound** [comment]
Will take a while to propagate around the ecosystem (a lot of packages depend on this one).

But two PRs that should help:
* https://github.com/electron/notarize/pull/140 very loud warning if you're using the legacy system
* https://github.com/electron/notarize/pull/141 semver major bump to default to the notarytool system

**Comment by MarshallOfSound** [comment]
Closing due to #141

**Comment by LaurentGENTY** [comment]
I have a particular question regarding the utilization of new tools: I'm currently employing electron-updater to facilitate the automatic updating of my application. I have undergone notarization for my previous version using the legacy method, whereas the new version has been notarized using notarytool. I am concerned whether the update process will proceed smoothly despite the divergence in notarization methods. Unfortunately, I am unable to conduct a test since I exclusively engage in notarizing my application in the production environment.

**Comment by thegnuu** [comment]
@LaurentGENTY I had the same issue a few weeks ago so i just "yoloed" an update in the middle of the night knowing that my app is usually not used at this time and everything worked without any issues. I use electron-builder to notarize (it uses this package) and electron-updater as well - so I guess there should not be any issues.

**Comment by LaurentGENTY** [comment]
Thank you! I believe the auto-update shouldn't encounter issues, considering that its functionality relies on certificates rather than the specific method of notarization 👍🏽

**Comment by Bansi23** [comment]
`CloudKit query for [...] failed due to "Record not found".
Could not find base64 encoded ticket in response [...]
The staple and validate action failed! Error 65.`

xcode : 14.3
All electron version is latest.
