### ISSUE TITLE
Team is not yet configured for notarization.

### ISSUE THREAD

**Issue by murrayee** [electron/notarize#205]
"@electron/notarize": "^2.3.0"
    "electron-builder": "^24.9.1"

{
  "logFormatVersion": 1,
  "jobId": "988a3f86-48f9-4713-a0ee-0227951a2d8c",
  "status": "Rejected",
  "statusSummary": "Team is not yet configured for notarization. Please contact Developer Programs Support at developer.apple.com under the topic Development and Technical / Other Development or Technical Questions.",
  "statusCode": 7000,
  "archiveFilename": "x'x'x'x.zip",
  "uploadDate": "2024-06-21T11:47:58.128Z",
  "sha256": "123123123",
  "ticketContents": null,
  "issues": null

}

Help !!!!!!!!

**Comment by TrofinSorin** [comment]
@murrayee Have you managed to fix this?

**Comment by techmultion** [comment]
Is there any updates for this?

**Comment by TrofinSorin** [comment]
Yes, you need to talk with Apple on this. They might have you blocked because of security issues. I had obfuscation so i had to remove it in order for them to allow me to notarize. This process can take 3-4 months from their side.

**Comment by hqxluoyang** [comment]
I have removed the relevant compression and obfuscation, but the error still occurs in the same way; it just returns faster now.

**Comment by hqxluoyang** [comment]
Can you help me, please? I'm waiting online.

**Comment by Sidrti** [comment]
Did anyone manage to solve this ? I have raised ticket to apple and it has been 1 month, i haven't received any solution from their end

**Comment by freakynit** [comment]
1. It's been almost 4 months for me since I first faced this issue. 
2. Contacted Apple developer support. They accepted it as an issue at their end.
3. More than 10 email threads exchanged after that waiting for the fix.
4. No fix given, no timelines given (not even tentative one), no refunds for Apple developer fee either.
5. Their response is always the same - a vague and unhelpful statement: `Our engineers are looking into this`.
6. This is a very old issue and a huge many people have got caught in this. Not a single person seems to have got this resolved. Referances:
  - https://developer.apple.com/forums/thread/118465
  - https://stackoverflow.com/questions/56660646/apple-notarization-error-team-is-not-yet-configured-for-notarization
  - https://github.com/fastlane/fastlane/issues/19686
  - https://forum.latenightsw.com/t/team-is-not-yet-configured-for-notarization-error/4714
  - https://developer.apple.com/forums/thread/735253

---

**Request everyone whoever gets caught in this, please put this issue and Apple's pathetic behavior towards fixing this on social media. Nothing else is working.**

In case anyone reading this have actually found a solution, please do share. Need it ASAP. 

Thanks..

> PS: My electron app which got caught in this: https://zenquery.app

**Comment by Sidrti** [comment]
Hi Nitin.
Its frustrating, I got my 2 accounts suspended without any notice.
I have made X post -
https://x.com/SS_Thakurr/status/1942495952742539533?t=TOiIQFNcTcOr1O4Yh-ioEw&s=19
Kindly retweet it.
I am sick of these people !
Its frustrating

**Comment by freakynit** [comment]
@Blaumaus It's Apple's issue. And what Im suspecting is that they are intentionally holding specific accounts under this issue. How do I know this?

The moment I started sharing this issue on social media, and threatened them with a class-action lawsuit for hurting my business, within 12 hours this was fixed. And other devs are still facing this. This means it's NOT a common issue in their infra, rather, they are **choosing**.

We devs, and other small companies, really need to drag Aple into the court. We truly have a winning case here.

**Comment by murrayee** [comment]
I did not succeed until the expiration date

**Comment by Blaumaus** [comment]
> [@Blaumaus](https://github.com/Blaumaus) It's Apple's issue. And what Im suspecting is that they are intentionally holding specific accounts under this issue. How do I know this?
> 
> The moment I started sharing this issue on social media, and threatened them with a class-action lawsuit for hurting my business, within 12 hours this was fixed. And other devs are still facing this. This means it's NOT a common issue in their infra, rather, they are **choosing**.
> 
> We devs, and other small companies, really need to drag Aple into the court. We truly have a winning case here.

What a joke company, treating devs who PAID for an account like that. I'll try to bring up the class-action lawsuit with them too to a customer support agent, maybe it works? Any tips to do it properly are appreciated

Are you on an individual or company account @freakynit? I'm on company one, and I think maybe if nothing works to purchase another dev membership, but an individual one? Kind of out of options at this point

**Comment by freakynit** [comment]
@Blaumaus Code-signing and notarization both have to come from same account (not strictly mandatory, but, Apple being Apple, have a very high probability of being rejected if not done this way). There's no harm in trying anyways. Takes a few minutes at max.

None. It's simply a stamp. Nothing related to technicals. But, Apple will show warning since the stamping account has changed. That in-place update would not work. It will be treated as a new app.

**Comment by KunKai100** [comment]
I am facing the same problem as you.

I was told that the notarization passed once, but upon retrying, I keep getting rejected due to the same error you faced.
How should I respond in this situation?
My Apple developer account was created less than 15 days ago, and my membership is currently active.

@freakynit 
Could you notarize my app?
I will pay the compensation.

**Comment by freakynit** [comment]
@KunKai100 Sorry, I have moved away from Apple dev ecosystem long back . 

They didn't fix it even after months of follow-ups and sooo many mails, and what's even worse, once they actually did fix it (after months of earlier follow-ups and many mails), they again started throwing this error within a few weeks of fixing... and then, never fixed it agian for me. So, I had no option left but to move on from Apple's ecosystem.

To the one incharge of this issue at Apple: 🖕🖕🖕 for destroying my sales, and subsequently, my product. If I had the money, I would have sued the fck out of you.

**Comment by Spartan-Determination** [comment]
Guess I get to join the party. Error code 7000, Team not config'd for notarization.

About 8 days ago I submitted my email begging them to flip the switch for me. Guess I'll have to wait 8 months to a year. 

And I paid them a developer fee for this miserable experience. What a joke.

**Comment by KunKai100** [comment]
@Spartan-Determination 
Me too.
I requested notarization again, but they still do not accept me.
I sent the email to apple developer team, but there is no resolution here....

How are you going to do now?

**Comment by bradeac** [comment]
I'm posting this so other devs hitting error 7000 know they're not alone, and so this gets some visibility outside the support ticket black hole.

Timeline:
- End of February 2026: first notarization attempts. All rejected with status code 7000
- March 1st: first support case opened
- Today, beginning of May: still blocked. Still error 7000

Four cases: 102833704616, 102836645198, 102842517951, 102865000390. Different advisors each time. I've uploaded my government ID twice. When I ask for a status, the answer is "I'll get back to you when I have news." Then silence.

My setup is fine. Team ID is Y564MF82K8. App is signed with Developer ID Application, hardened runtime, secure timestamp, no get-task-allow, deep verify clean. Apple rejects the submission before inspecting the binary. The block is on Apple's side. Somebody needs to push a button, but they cannot agree who needs to push it, so they just pass it from one department to another.

The "correct escalation path" doesn't work. Quinn (Apple DTS engineer) keeps saying on this forum that error 7000 is administrative and the path is Developer Program Support (https://developer.apple.com/forums/thread/118465?answerId=379585022#379585022). I followed that path four times. The cases just sit there.

Threads on this forum about error 7000 go back to 2019. Six years. Devs report cases stuck for weeks, months, with the same scripted responses. Apple knows. Apple does nothing.

I'm a solo dev and I want to do a proper launch of my SaaS on all major desktop platforms. I paid the $99. I built the app. I signed every agreement. I cannot launch on macOS because Apple's departments cannot agree on who needs to push a button.

If anyone here has actually unblocked error 7000, please share what worked. The official path obviously doesn't.

**Comment by Spartan-Determination** [comment]
Getting on one month now. My app has just been sitting gathering dust for a month while no movement occurs on getting approved for notarization.

Brad, we do appreciate the effort you're putting into getting visibility on this.

**Comment by tddyco** [comment]
Hi all! Sharing a glimmer of hope here –

As much as Apple insists that Error 7000 cannot be resolved without contacting them, it's not always true. In my case, when notarization randomly started failing, I was still able to successfully notarize a "hello world" app. This enabled me to find and fix the issue with my actual app.

If you're getting Error 7000 and haven't tried notarizing an empty app, try it with a coding agent and see if Apple accepts it.

**Comment by Spartan-Determination** [comment]
Hi Teddy - seeing the notification on yours reminded me to post here again. To my immense relief my Status Code 7000 block was lifted a few days ago. I badgered an engineer at WWDC in the forums and it got flipped. (May be unrelated)

So yes there is hope!

**Comment by freakynit** [comment]
@tddyco 
"""This enabled me to find and fix the issue with my actual app""" ... what was the issue? 

And I have confirmed from Apple itself that this error 7000 is on their end, not developer's end. My earlier app started to get notarized successfully without me needing to change anything in the code. But then after a few days, started to fail again, again, no change in code or even the system. It's not a code issue on app submitter's part. Rather, Apple's end.

As we can see from @Spartan-Determination comment above, it's a switch they can control and choose to flip or not.

**Comment by tddyco** [comment]
I can't share the specific issue we encountered, but I can confirm that in our case it was 100% a code side problem, which went away instantly once we solved it. From my perspective, Error 7000 is essentially Apple's version of a shadowban – they intentionally obfuscate the cause in order to make it difficult to resolve.

I'm sure many (most?) cases do require Apple's direct intervention in order to resolve the error, but in our case it did not. The quick and easy way to determine which bucket you fall in is to submit an empty "hello world" style app bundle and see if it gets notarized or not. If a blank app successfully notarizes under your team, then it's a code side issue.

**Comment by bradeac** [comment]
> Hi all! Sharing a glimmer of hope here –
> 
> As much as Apple insists that Error 7000 cannot be resolved without contacting them, it's not always true. In my case, when notarization randomly started failing, I was still able to successfully notarize a "hello world" app. This enabled me to find and fix the issue with my actual app.
> 
> If you're getting Error 7000 and haven't tried notarizing an empty app, try it with a coding agent and see if Apple accepts it.

Thanks for pointing this out! I tried it, and it worked! Both the empty app and the real app were accepted. It remains to be seen if this is something permanent or if they will start rejecting the real app again in the future. I haven't received any notice from Apple that they resolved my situation.

**Comment by freakynit** [comment]
@tddyco Thanks for this. That blank app test does give some glimmer of hope, although I have moved away from Apple's dev ecosystem long time  ago due to this very issue.

Thanks @bradeac for testing it out.

In case anyone else here can run this test, do let us know of the results.

**Comment by sapph1re** [comment]
Data point for the cluster: individual team enrolled 2026-06-19 (Mexico region), first notarytool submission 2026-06-20 → statusCode 7000, and every submission since — 15 of 15 as of today — rejected the same way, `issues: null`, file never analyzed. Control test: an unmodified copy of /bin/ls signed with our valid Developer ID cert was rejected identically, so it's the team flag, not the payload. Support case 102922992178 open since June 23, escalated to engineering July 7, no engineering response since. Apple DTS replied on our forum thread (837536) confirming nothing is missing on our side. Posting here since this thread seems to be where the 2026 new-team cases are being tracked — will report back if/when the flag flips (we run a daily signed-probe canary).
